name: Dev Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
    dev-release:
      uses: ./.github/workflows/terraform.yml
      with:
        environment: dev
      secrets:
        inherit

    approve-prod-deploy:
      environment: prod
      runs-on: ubuntu-latest
      permissions:
        contents: write
        actions: write
      needs: [dev-release]
      steps:
        - run: echo "Prod Deployment Approved"
        
        - name: Checkout Actions
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            
        - name: Trigger Prod Workflow
          uses: actions/github-script@v6
          if: github.ref == 'refs/heads/main'
          with:
            github-token: ${{ secrets.GH_TOKEN }}
            script: |
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'prod-release.yml'
              })
